### ISSUE TITLE
[PHASE 2]派出所落户

### ISSUE THREAD

**Issue by mingyangSunshine** [XiaoxingChen/shanghai_luohu#3]
辖区派出所--新镇派出所
-------
- [x] 实有人口登记
- [x] 落户蓝表批复《关于接受非上海生源高校毕业生的通知》
- [x] 户籍证明
- [x] 就业报到证
- [x] 社区公共户告知单
- [x] 《高校毕业生申报户口证明信》   *用人单位办理*
- [x] [审批结果在线查询](http://zwdt.sh.gov.cn/zwdtSW/zwdtSW/userIdNo/userIdNo.jsp#)
- [x] 新镇派出所申请“社区公共户”

~~公共户申请成功后：~~
- [x] ~~公安机关签发《户口类审批意见决定书》~~
- [x] ~~学校户政科开具《准迁证明》，派出所办理迁出手续~~
- [x] ~~打印《户口迁移证》~~
- [x] ~~居住地派出所办理落户~~

[“社区公共户”服务告知单.pdf](https://github.com/XiaoxingChen/shanghai_luohu/files/3475053/default.pdf)
[非上海生源高校毕业生落“社区公共户”流程.pdf](https://github.com/XiaoxingChen/shanghai_luohu/files/3475058/default.pdf)

**Comment by XiaoxingChen** [comment]
That's really cool!

**Comment by mingyangSunshine** [comment]
> That's really cool!

no one can be cooler than you!

**Comment by mingyangSunshine** [comment]
everything done.
No need for the migration of Hukou since we have migrated it to school.

**Comment by XiaoxingChen** [comment]
@mingyangSunshine Awesome man! Excellent work!
